### ISSUE TITLE
Stopped working in January

### ISSUE THREAD

**Issue by porridge** [kantord/pricedb#3]
I just noticed that the last update time was January 30th.
Did the travis job go down?

Thank you for providing this service so far! This is super useful!

**Comment by kantord** [comment]
apparently the features in travis needed for this are no longer free. I am not planning to pay for it if there is any alternative so I guess it will have to be rewritten using GitHub actions maybe

**Comment by kantord** [comment]
should be fixed now, at the very least now you have up to date data, we will have to wait some days to see if the update schedule indeed works every day

**Comment by kantord** [comment]
yup, I can confirm it works fine now!
